# Generated by Django 4.1.2 on 2023-01-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_image1_product_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='discount',
        ),
    ]
