# Generated by Django 4.1.2 on 2023-01-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='originalprice',
        ),
    ]
